# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-08 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analyzer',
            new_name='Nums',
        ),
    ]
